[package]
name = "fizyr-rpc"
version = "0.1.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
edition = "2018"

[dependencies]
futures = "0.3.5"
byteorder = "1.3.4"
thiserror = "1.0.20"

[dev-dependencies]
assert2 = "0.3.1"
async-std = { version = "1.6.3", features = ["attributes"] }
