[package]
name = "fizyr-rpc"
description = "Native Rust implementation of the Fizyr RPC protocol"
version = "0.8.0"
authors = [
	"Fizyr B.V. <info@fizyr.com>",
	"Maarten de Vries <maarten@de-vri.es>",
]

license = "BSD-2-Clause OR Apache-2.0"
repository = "https://github.com/fizyr/fizyr-rpc"
documentation = "https://docs.rs/fizyr-rpc"
readme = "README.md"
publish = ["crates-io"]

keywords = ["rpc", "shared-memory"]
categories = ["asynchronous", "network-programming"]

rust-version = "1.85"
edition = "2024"

[features]
macros = ["fizyr-rpc-macros"]
tcp = ["tokio/net"]
unix-seqpacket = ["tokio-seqpacket", "memfile"]
unix-stream = ["tokio/net"]

[dependencies]
filedesc = { version = "0.6.1" }
memfile = { version = "0.3.0", optional = true }
tokio = { version = "1.32.0", features = ["rt", "sync"] }
tokio-seqpacket = { version = "0.7.0", optional = true }
fizyr-rpc-macros = { version = "0.8.0", path = "macros", optional = true }

[dev-dependencies]
assert2 = "0.3.11"
clap = { version = "4.4.4", features = ["derive"] }
tokio = { version = "1.32.0", features = ["macros"] }

[[example]]
name = "tcp-client"
required-features = ["tcp"]

[[example]]
name = "tcp-server"
required-features = ["tcp"]

[[example]]
name = "unix-stream-client"
required-features = ["unix-stream"]

[[example]]
name = "unix-stream-server"
required-features = ["unix-stream"]

[[example]]
name = "unix-seqpacket-client"
required-features = ["unix-seqpacket"]

[[example]]
name = "unix-seqpacket-server"
required-features = ["unix-seqpacket"]

[package.metadata.docs.rs]
features = ["macros", "tcp", "unix-stream", "unix-seqpacket"]

[workspace]
members = ["macros", "macros-tests"]
