[package]
name = "fizyr-rpc"
description = "Native Rust implementation of the Fizyr RPC protocol"
version = "0.3.1"
authors = [
	"Fizyr B.V. <info@fizyr.com>",
	"Maarten de Vries <maarten@de-vri.es>",
]

license = "BSD-2-Clause OR Apache-2.0"
repository = "https://github.com/fizyr/fizyr-rpc-rs"
documentation = "https://docs.rs/fizyr-rpc"
readme = "README.md"

keywords = ["rpc", "shared-memory"]
categories = ["asynchronous", "network-programming"]

edition = "2018"

[features]
tcp = ["tokio/net"]
unix-stream = ["tokio/net"]
unix-seqpacket = ["filedesc", "tokio-seqpacket"]

[dependencies]
byteorder = "1.3.4"
filedesc = { version = "0.3.0", optional = true }
thiserror = "1.0.20"
tokio = { version = "1.0.0", features = ["rt", "sync"] }
tokio-seqpacket = { version = "0.5.0", optional = true }

[dev-dependencies]
assert2 = "0.3.3"
tokio = { version = "1.0.0", features = ["macros"] }
fizyr-rpc = { path = ".", features = ["unix-seqpacket", "unix-stream", "tcp"] }
structopt = "0.3.18"
memfd = "0.3.0"

[package.metadata.docs.rs]
features = ["tcp", "unix-stream", "unix-seqpacket"]
