[package]
name = "fizyr-rpc"
version = "0.1.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
edition = "2018"

[features]
tcp = ["tokio/tcp"]
unix = ["tokio/uds"]

[dependencies]
tokio = { version = "0.2.0", features = ["rt-core", "sync", "io-util"] }
byteorder = "1.3.4"
thiserror = "1.0.20"

[dev-dependencies]
assert2 = "0.3.2"
tokio = { version = "0.2.0", features = ["rt-core", "uds", "macros"] }
fizyr-rpc = { path = ".", features = ["unix"] }
