[package]
name = "macros-tests"
version = "0.1.0"
edition = "2018"

[dependencies]
fizyr-rpc = { path = "..", features = ["macros", "unix-stream"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
