name: tests
on:
  push: { branches: "main" }
  pull_request: { branches: "*" }

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features --color=always
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --color=always
